AdminIndex:
  path: /admin
  controller: '\ComponentBundle\Extending\Admin\Mvc\Pub\Index::container'

AdminSiteSettings:
  path: /admin/settings
  controller: '\ComponentBundle\Extending\Admin\Mvc\Pub\Settings::container'

AdminOAuthServices:
  path: /admin/oauth
  controller: '\ComponentBundle\Extending\Admin\Mvc\Pub\OAuth::container'

AdminRouteFilters:
  path: /admin/route-filters
  controller: '\ComponentBundle\Extending\Admin\Mvc\Pub\RouteFilters::container'

AdminCensorWords:
  path: /admin/censor-words
  controller: '\ComponentBundle\Extending\Admin\Mvc\Pub\CensorWords::container'

AdminNativeApi:
  path: /admin/api
  controller: '\ComponentBundle\Extending\Admin\Mvc\Pub\NativeApi::container'

AdminForums:
  path: /admin/forums
  controller: '\ComponentBundle\Extending\Admin\Mvc\Pub\Forums::container'

AdminUsers:
  path: /admin/users
  controller: '\ComponentBundle\Extending\Admin\Mvc\Pub\Users::container'

AdminAddons:
  path: /admin/addons
  controller: '\ComponentBundle\Extending\Admin\Mvc\Pub\Addons::container'

AdminAttachments:
  path: /admin/attachments
  controller: '\ComponentBundle\Extending\Admin\Mvc\Pub\Attachments::container'

AdminTheme:
  path: /admin/theme
  controller: '\ComponentBundle\Extending\Admin\Mvc\Pub\Theme::container'

AdminTemplates:
  path: /admin/templates
  controller: '\ComponentBundle\Extending\Admin\Mvc\Pub\Templates::container'

AdminLanguages:
  path: /admin/languages
  controller: '\ComponentBundle\Extending\Admin\Mvc\Pub\Languages::container'

AdminEditor:
  path: /admin/editor
  controller: '\ComponentBundle\Extending\Admin\Mvc\Pub\Editor::container'

AdminLogs:
  path: /admin/logs
  controller: '\ComponentBundle\Extending\Admin\Mvc\Pub\Logs::container'

AdminCommonBundle:
  path: /admin/common
  controller: '\ComponentBundle\Extending\Admin\Mvc\Pub\Common::container'
